package com.facility.management.model.usage;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.facility.management.model.facility.Facility;

/**
 * Inspection generated by hbm2java
 */
public class InspectionImpl implements java.io.Serializable, Inspection {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4172661170922912342L;
	private Integer inspectionId;
	private Facility facility;
	private Date inspectionDate;
	private String inspectionResult;

	public InspectionImpl() {
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#getInspectionId()
	 */
	@Override
	public Integer getInspectionId() {
		return this.inspectionId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#setInspectionId(java.lang.Integer)
	 */
	@Override
	public void setInspectionId(Integer inspectionId) {
		this.inspectionId = inspectionId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#getFacility()
	 */
	@Override
	public Facility getFacility() {
		return this.facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#setFacility(com.facility.management.model.Facility)
	 */
	@Override
	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#getInspectionDate()
	 */
	@Override
	public Date getInspectionDate() {
		return this.inspectionDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#setInspectionDate(java.util.Date)
	 */
	@Override
	public void setInspectionDate(Date inspectionDate) {
		this.inspectionDate = inspectionDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#getInspectionResult()
	 */
	@Override
	public String getInspectionResult() {
		return this.inspectionResult;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Inspection#setInspectionResult(java.lang.String)
	 */
	@Override
	public void setInspectionResult(String inspectionResult) {
		this.inspectionResult = inspectionResult;
	}

}
