package com.facility.management.model.usage;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * LeasePayment generated by hbm2java
 */
public class LeasePaymentImpl implements java.io.Serializable, LeasePayment {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3255528875403582696L;
	private Integer paymentId;
	private LeaseInfo leaseInfo;
	private BigDecimal amountDue;
	private Date paymentDate;
	private BigDecimal amountPaid;
	private Date dueDate;

	public LeasePaymentImpl() {
	}

	public LeasePaymentImpl(LeaseInfo leaseInfo, BigDecimal amountDue,
			Date paymentDate, BigDecimal amountPaid, Date dueDate) {
		this.leaseInfo = leaseInfo;
		this.amountDue = amountDue;
		this.paymentDate = paymentDate;
		this.amountPaid = amountPaid;
		this.dueDate = dueDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getPaymentId()
	 */
	@Override
	public Integer getPaymentId() {
		return this.paymentId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setPaymentId(java.lang.Integer)
	 */
	@Override
	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getLeaseInfo()
	 */
	@Override
	public LeaseInfo getLeaseInfo() {
		return this.leaseInfo;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setLeaseInfo(com.facility.management.model.LeaseInfo)
	 */
	@Override
	public void setLeaseInfo(LeaseInfo leaseInfo) {
		this.leaseInfo = leaseInfo;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getAmountDue()
	 */
	@Override
	public BigDecimal getAmountDue() {
		return this.amountDue;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setAmountDue(java.math.BigDecimal)
	 */
	@Override
	public void setAmountDue(BigDecimal amountDue) {
		this.amountDue = amountDue;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getPaymentDate()
	 */
	@Override
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setPaymentDate(java.util.Date)
	 */
	@Override
	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getAmountPaid()
	 */
	@Override
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setAmountPaid(java.math.BigDecimal)
	 */
	@Override
	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#getDueDate()
	 */
	@Override
	public Date getDueDate() {
		return this.dueDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.LeasePayment#setDueDate(java.util.Date)
	 */
	@Override
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

}
