package com.facility.management.model.usage;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import com.facility.management.model.facility.Facility;

/**
 * PurchaseInfo generated by hbm2java
 */
public class PurchaseInfoImpl implements java.io.Serializable, PurchaseInfo {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4394498679387209185L;
	private Integer purchaseId;
	private Facility facility;
	private Owner owner;
	private Date purchaseDate;
	private BigDecimal puchasePrice;

	public PurchaseInfoImpl() {
	}

	public PurchaseInfoImpl(Facility facility, Owner owner, Date purchaseDate,
			BigDecimal puchasePrice) {
		this.facility = facility;
		this.owner = owner;
		this.purchaseDate = purchaseDate;
		this.puchasePrice = puchasePrice;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#getPurchaseId()
	 */
	@Override
	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#setPurchaseId(java.lang.Integer)
	 */
	@Override
	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#getFacility()
	 */
	@Override
	public Facility getFacility() {
		return this.facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#setFacility(com.facility.management.model.Facility)
	 */
	@Override
	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#getOwner()
	 */
	@Override
	public Owner getOwner() {
		return this.owner;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#setOwner(com.facility.management.model.Owner)
	 */
	@Override
	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#getPurchaseDate()
	 */
	@Override
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#setPurchaseDate(java.util.Date)
	 */
	@Override
	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#getPuchasePrice()
	 */
	@Override
	public BigDecimal getPuchasePrice() {
		return this.puchasePrice;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.PurchaseInfo#setPuchasePrice(java.math.BigDecimal)
	 */
	@Override
	public void setPuchasePrice(BigDecimal puchasePrice) {
		this.puchasePrice = puchasePrice;
	}

}
