package com.facility.management.model.maintenance;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.facility.management.model.facility.Facility;

/**
 * MaintenanceRequest generated by hbm2java
 */
public class MaintenanceRequestImpl implements java.io.Serializable, MaintenanceRequest {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6960981087570567871L;
	private Integer mainReqId;
	private Facility facility;
	private Date requestDate;
	private String nameOfRequester;
	private String detail;
	private String email;
	private String subject;

	public MaintenanceRequestImpl() {
	}

	public MaintenanceRequestImpl(Facility facility, Date requestDate,
			String nameOfRequester, String detail, String email, String subject) {
		this.facility = facility;
		this.requestDate = requestDate;
		this.nameOfRequester = nameOfRequester;
		this.detail = detail;
		this.email = email;
		this.subject = subject;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getMainReqId()
	 */
	@Override
	public Integer getMainReqId() {
		return this.mainReqId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setMainReqId(java.lang.Integer)
	 */
	@Override
	public void setMainReqId(Integer mainReqId) {
		this.mainReqId = mainReqId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getFacility()
	 */
	@Override
	public Facility getFacility() {
		return this.facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setFacility(com.facility.management.model.Facility)
	 */
	@Override
	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getRequestDate()
	 */
	@Override
	public Date getRequestDate() {
		return this.requestDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setRequestDate(java.util.Date)
	 */
	@Override
	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getNameOfRequester()
	 */
	@Override
	public String getNameOfRequester() {
		return this.nameOfRequester;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setNameOfRequester(java.lang.String)
	 */
	@Override
	public void setNameOfRequester(String nameOfRequester) {
		this.nameOfRequester = nameOfRequester;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getDetail()
	 */
	@Override
	public String getDetail() {
		return this.detail;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setDetail(java.lang.String)
	 */
	@Override
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getEmail()
	 */
	@Override
	public String getEmail() {
		return this.email;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setEmail(java.lang.String)
	 */
	@Override
	public void setEmail(String email) {
		this.email = email;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#getSubject()
	 */
	@Override
	public String getSubject() {
		return this.subject;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceRequest#setSubject(java.lang.String)
	 */
	@Override
	public void setSubject(String subject) {
		this.subject = subject;
	}

}
