package com.facility.management.model.maintenance;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Maintenance generated by hbm2java
 */
public class MaintenanceImpl implements java.io.Serializable, Maintenance {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6986079813097308454L;
	private Integer maintenanceId;
	private MaintenanceRequest maintenanceRequest;
	private String workerName;
	private String workerPhone;
	private Date startDateTime;
	private Date endDateTime;
	private MaintenanceCost maintenanceCost;

	public MaintenanceImpl() {
	}

	public MaintenanceImpl(MaintenanceRequest maintenanceRequest, String workerName,
			String workerPhone, Date startDateTime, Date endDateTime,
			MaintenanceCost maintenanceCost) {
		this.maintenanceRequest = maintenanceRequest;
		this.workerName = workerName;
		this.workerPhone = workerPhone;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.maintenanceCost = maintenanceCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getMaintenanceId()
	 */
	@Override
	public Integer getMaintenanceId() {
		return this.maintenanceId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setMaintenanceId(java.lang.Integer)
	 */
	@Override
	public void setMaintenanceId(Integer maintenanceId) {
		this.maintenanceId = maintenanceId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getMaintenanceRequest()
	 */
	@Override
	public MaintenanceRequest getMaintenanceRequest() {
		return this.maintenanceRequest;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setMaintenanceRequest(com.facility.management.model.MaintenanceRequestImpl)
	 */
	@Override
	public void setMaintenanceRequest(MaintenanceRequest maintenanceRequest) {
		this.maintenanceRequest = maintenanceRequest;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getWorkerName()
	 */
	@Override
	public String getWorkerName() {
		return this.workerName;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setWorkerName(java.lang.String)
	 */
	@Override
	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getWorkerPhone()
	 */
	@Override
	public String getWorkerPhone() {
		return this.workerPhone;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setWorkerPhone(java.lang.String)
	 */
	@Override
	public void setWorkerPhone(String workerPhone) {
		this.workerPhone = workerPhone;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getStartDateTime()
	 */
	@Override
	public Date getStartDateTime() {
		return this.startDateTime;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setStartDateTime(java.util.Date)
	 */
	@Override
	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getEndDateTime()
	 */
	@Override
	public Date getEndDateTime() {
		return this.endDateTime;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setEndDateTime(java.util.Date)
	 */
	@Override
	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#getMaintenanceCost()
	 */
	@Override
	public MaintenanceCost getMaintenanceCost() {
		return this.maintenanceCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.Maintenance#setMaintenanceCost(com.facility.management.model.MaintenanceCost)
	 */
	@Override
	public void setMaintenanceCost(MaintenanceCost maintenanceCost) {
		this.maintenanceCost = maintenanceCost;
	}

}
