package com.facility.management.model.maintenance;
// Generated Mar 14, 2016 11:20:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * MaintenanceCost generated by hbm2java
 */
public class MaintenanceCostImpl implements java.io.Serializable, MaintenanceCost {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2226336795055764970L;
	private Integer maintenanceId;
	private Maintenance maintenance;
	private BigDecimal materialCost;
	private BigDecimal laborCost;
	private BigDecimal totalCost;
	private String isPaid;

	public MaintenanceCostImpl() {
	}

	public MaintenanceCostImpl(Maintenance maintenance) {
		this.maintenance = maintenance;
	}

	public MaintenanceCostImpl(Maintenance maintenance, BigDecimal materialCost,
			BigDecimal laborCost, BigDecimal totalCost, String isPaid) {
		this.maintenance = maintenance;
		this.materialCost = materialCost;
		this.laborCost = laborCost;
		this.totalCost = totalCost;
		this.isPaid = isPaid;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getMaintenanceId()
	 */
	@Override
	public Integer getMaintenanceId() {
		return this.maintenanceId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setMaintenanceId(java.lang.Integer)
	 */
	@Override
	public void setMaintenanceId(Integer maintenanceId) {
		this.maintenanceId = maintenanceId;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getMaintenance()
	 */
	@Override
	public Maintenance getMaintenance() {
		return this.maintenance;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setMaintenance(com.facility.management.model.MaintenanceImpl)
	 */
	@Override
	public void setMaintenance(Maintenance maintenance) {
		this.maintenance = maintenance;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getMaterialCost()
	 */
	@Override
	public BigDecimal getMaterialCost() {
		return this.materialCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setMaterialCost(java.math.BigDecimal)
	 */
	@Override
	public void setMaterialCost(BigDecimal materialCost) {
		this.materialCost = materialCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getLaborCost()
	 */
	@Override
	public BigDecimal getLaborCost() {
		return this.laborCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setLaborCost(java.math.BigDecimal)
	 */
	@Override
	public void setLaborCost(BigDecimal laborCost) {
		this.laborCost = laborCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getTotalCost()
	 */
	@Override
	public BigDecimal getTotalCost() {
		return this.totalCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setTotalCost(java.math.BigDecimal)
	 */
	@Override
	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#getIsPaid()
	 */
	@Override
	public String getIsPaid() {
		return this.isPaid;
	}

	/* (non-Javadoc)
	 * @see com.facility.management.model.MaintenanceCost#setIsPaid(java.lang.String)
	 */
	@Override
	public void setIsPaid(String isPaid) {
		this.isPaid = isPaid;
	}

}
